### ISSUE TITLE
Coloring breaks on template literal embedded expressions

### ISSUE THREAD

**Issue by gersomvg** [neurosnap/language-csjs#1]
Thanks, awesome that you built this plugin! Unfortunately, the colouring breaks on an expression. See attached image.
<img width="409" alt="screen shot 2016-06-08 at 12 12 31" src="https://cloud.githubusercontent.com/assets/8234283/15890953/7c5b3c50-2d72-11e6-8c9f-8cd21567fa6d.png">

**Comment by gersomvg** [comment]
I think it has to do with the syntax highlighting from the css grammar. It looks like the `}` in `${constants.radius}` is being interpreted as the end of the css selector scope.

I have already played around a little bit, but can't get it to work.

**Comment by neurosnap** [comment]
Thanks for the issue, yes I have noticed this as well.  I've been trying to override the CSS grammar when a js variable is detected but at this point I haven't found a solution.  I'll keep looking into this and see if I can't find a fix.

https://github.com/neurosnap/language-csjs/blob/master/grammars/csjs.cson#L12

**Comment by neurosnap** [comment]
I was able to fix this javascript expression syntax highlighting error.  Please update your package and let me know if it works for you.

Thanks!

**Comment by gersomvg** [comment]
Nice!! It works :) Thanks a lot!
